### ISSUE TITLE
IP address mismatch, certificate is not valid

### ISSUE THREAD

**Issue by PatrikPatrik2** [fondberg/pyeasee#29]
Hi,
I tried the script using:
python -m pyeasee -u +46xxxxxxxx -p password -ci

but then I only get an error:
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.easee.cloud:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '54.xxx.xxx.xxx'. (_ssl.c:1091)")]
2020-10-24 23:18:31,125 asyncio ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efdebf39ad0>

What have I done wrong?

**Comment by olalid** [comment]
Do you still have this problem, i.e. was it a temporary problem?
If not, perhaps you have an old incompatible version of aoihttp library and or pyton?
You can also try adding -d option to get more debug printouts.

**Comment by PatrikPatrik2** [comment]
it was a temporary problem, so now it works.
However, I am a beginner in Python, and I need some help - I want to write two pyton scripts one that enables charging and one that disables the charging (i.e. the code for that, such that I can integrate this in a larger python script). How do I do that? I tried to run the small sample but I could not get that to work.

**Comment by olalid** [comment]
Quick example:
'''
import sys
import asyncio
from pyeasee import Easee, Charger


async def main():
    if len(sys.argv) != 4:
        print(f"Usage {sys.argv[0]} username password charger_id")
        return

    username = sys.argv[1]
    password = sys.argv[2]
    charger_id = sys.argv[3]
    
    easee = Easee(username, password)
    chargers = await easee.get_chargers()
    for charger in chargers:
        if charger.id == charger_id:
            print(f"Sending pause command to charger: {charger.id}")
            await charger.pause()
        
asyncio.run(main())
'''

**Comment by PatrikPatrik2** [comment]
Thanks!!!!!!

I got:

Bad request service (400: {'errorCode': 410, 'errorCodeName': 'ChargerDisconnected', 'type': None, 'title': 'Charger disconnected', 'status': 400, 'detail': '[Empty in production]', 'instance': None} https://api.easee.cloud/api/chargers/EH517722/commands/pause_charging)

The charging cable is not connected - is this why I got the error?
If I do not want the charging to start, even if the cable is connected, until I send a command - what commands should I use?

**Comment by olalid** [comment]
Yes, if the charger is not connected to a car the easee cloud API will return an error.

To stop the charger from starting you could set the dynamic circuit current to anything between 0 and 5A (6A and higher will make the charger start).
e.g. charger.set_dynamic_charger_circuit_current(5)

**Comment by olalid** [comment]
Closing since the issue was probably a temporary problem with the cloud API.
