### ISSUE TITLE
Hourly consumption data

### ISSUE THREAD

**Issue by borlum** [fondberg/pyeasee#33]
First: fantastic job. Had my charger installed a month ago, wanted to now fiddle with the API as I am not a fan of the app. Found your package before I even hit the easee API documentation. Kudos on the work here!

I am missing one thing, but might do a PR on this; hourly consumption data:

```
/api/chargers/{id}/usage/hourly/{from}/{to}
Get hourly aggregated usage between two dates
```

:1st_place_medal:

**Comment by olalid** [comment]
I think this would be the same thing as this api:
/api/sessions/charger/{chargerId}/sessions/{from}/{to}
Since we are using the sessions API for other consumption data we perhaps should aim for that instead?
